create table tb_address (
    id int8 generated by default as identity,
    cep varchar(255),
    number int4,
    street varchar(255),
    city_id int8,
    client_id int8,
    primary key (id)
);

create table tb_category (
    id int8 generated by default as identity,
    name varchar(255),
    primary key (id)
);

create table tb_cellphone (
    client_id int8 not null,
    cellphone varchar(255)
);

create table tb_city (
    id int8 generated by default as identity,
    name varchar(255),
    state_id int8,
    primary key (id)
);

create table tb_client (
    id int8 generated by default as identity,
    cpf_cnpj varchar(255),
    deleted boolean not null,
    email varchar(255),
    name varchar(255),
    type int4,
    primary key (id)
);

create table tb_credit_card_payment (
    number_of_installemnts int4,
    order_id int8 not null,
    primary key (order_id)
);

create table tb_order (
    id int8 generated by default as identity,
    instant timestamp,
    client_id int8,
    delivery_address_id int8,
    primary key (id)
);

create table tb_order_item (
    discount float8,
    price float8,
    quantity int4,
    product_id int8 not null,
    order_id int8 not null,
    primary key (order_id, product_id)
);

create table tb_payment (
    order_id int8 not null,
    payment_status int4,
    primary key (order_id)
);

create table tb_product (
    id int8 generated by default as identity,
    name varchar(255),
    price float8,
    primary key (id)
);

create table tb_product_category (
    product_id int8 not null,
    category_id int8 not null
);

create table tb_slip_payment (
    due_date timestamp,
    pay_date timestamp,
    order_id int8 not null,
    primary key (order_id)
);

create table tb_state (
    id int8 generated by default as identity,
    name varchar(255),
    primary key (id)
);

alter table if exists tb_client
    add constraint UK_tbu74oe5ntiego6pu36jfokha unique (email);

alter table if exists tb_address
    add constraint FKpm4x3qy2wea2p4ea7bs217nr5
    foreign key (city_id)
    references tb_city;

alter table if exists tb_address
    add constraint FKmgkeodciwq4rofwws5m08v1yh
    foreign key (client_id)
    references tb_client;

alter table if exists tb_cellphone
    add constraint FKtaj9h8p880wy0sabnhqtsgst8
    foreign key (client_id)
    references tb_client;

alter table if exists tb_city
    add constraint FK1rn7oty4mwqviyw8vk67crapo
    foreign key (state_id)
    references tb_state;

alter table if exists tb_credit_card_payment
    add constraint FKf968osuymhatr13f1gx3pdom9
    foreign key (order_id)
    references tb_payment;

alter table if exists tb_order
    add constraint FK7c9of0p9ogx0w8sfrebt4n9kk
    foreign key (client_id)
    references tb_client;

alter table if exists tb_order
    add constraint FK85tw4vl1jrr095yn152toe1gs
    foreign key (delivery_address_id)
    references tb_address;

alter table if exists tb_order_item
    add constraint FK4h5xid5qehset7qwe5l9c997x
    foreign key (product_id)
    references tb_product;

alter table if exists tb_order_item
    add constraint FKgeobgl2xu916he8vhljktwxnx
    foreign key (order_id)
    references tb_order;

alter table if exists tb_payment
    add constraint FKokaf4il2cwit4h780c25dv04r
    foreign key (order_id)
    references tb_order;

alter table if exists tb_product_category
    add constraint FK5r4sbavb4nkd9xpl0f095qs2a
    foreign key (category_id)
    references tb_category;

alter table if exists tb_product_category
    add constraint FKgbof0jclmaf8wn2alsoexxq3u
    foreign key (product_id)
    references tb_product;

alter table if exists tb_slip_payment
    add constraint FKeme177r4b4j01okbb4ehloxwk
    foreign key (order_id)
    references tb_payment;